# Build Model {.unnumbered}

Now that we have both the surface metrics and training points, now it is finally time to start calculating wetland probabilities. The first step is building, or training, the model. This allows the model to figure out how to calculate probabilities and make predictions.

See `build_model` section for the function

## Model options

The model options are decision tree, random forest, logistic regression, and k-nearest neighbors. More on these types of models in the coming pages The default setting is to run random forest with `n=200` trees. To change this, the user would just need to type `model_type =` and choose their selection of `c("forest", "tree", "glm", "knn")`.

Also, depending on the model choice, you might also have to add an extra input, `model_params`. If the choice is `knn`, then you would have to add in the number of neighbors. For example, if you want to use ten neighbors, just type in `model_params = list(k = 10)`. If you want to use a different number of tress in the random forest than `n=200`, just type in `model_params = list(ntree = )` , with the selected choice of trees after the equal sign.

## Parameters

| Input              | Description                                                                                                                                                                                                                            |
|----------------------|--------------------------------------------------|
| `in_rasts`         | List input that contains all the rasters that are chosen to be included in the model                                                                                                                                                   |
| `poly_inputs`      | List input that contains the polygons that are chosen to be included in the model, if any                                                                                                                                              |
| `train`            | Spatial vector input of the training points                                                                                                                                                                                            |
| `ref_raster`       | Spatial raster input of the reference raster, which is used to align all of the other inputs. The DEM is usually a good choice here                                                                                                    |
| `model_type`       | String input indicating type of machine learning model. Options include "forest", "tree", "glm", and "knn"                                                                                                                             |
| `model_params`     | List input representing necessary parameters to the model. Depending on the model, it may require an extra input, such as the number of trees or number of neighbors.                                                                  |
| `class_field_name` | String input indicating the field where the wetland classification is. If calculated training points using the `build_train_pts` function above, this input may be skipped. However, very important if training points came externally |
